version: '3.7'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8083:80
    networks:
      - mysql-db

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: shiros_inventory
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - mysql-db

  server:
    depends_on:
      - mysql
    build: ./server/
    restart: always
    ports:
      - "3000:3000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/shiros_inventory?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false
    networks:
      - mysql-db

  client:
    build: ./client/
    restart: always
    ports:
      - "8080:5000"
    networks:
      - mysql-db

networks:
  mysql-db:
    driver: bridge